export const FETCH_PHRASES_PENDING = 'FETCH_PHRASES_PENDING';
export const FETCH_PHRASES_SUCCESS = 'FETCH_PHRASES_SUCCESS';
export const FETCH_PHRASES_ERROR = 'FETCH_PHRASES_ERROR';

export const ADD_PHRASE_SUCCESS = 'ADD_PHRASE_SUCCESS';
export const ADD_PHRASE_ERROR = 'ADD_PHRASE_ERROR';
export const UPDATE_PHRASE_SUCCESS = 'UPDATE_PHRASE_SUCCESS';
export const UPDATE_PHRASE_ERROR = 'UPDATE_PHRASE_ERROR';
export const DELETE_PHRASE_SUCCESS = 'DELETE_PHRASE_SUCCESS';
export const DELETE_PHRASE_ERROR = 'DELETE_PHRASE_ERROR';

export const PHRASES_ASYNC_STORAGE = 'PHRASES_ASYNC_STORAGE';

export const ADD_PICTOGRAM_TO_PHRASE = 'ADD_PICTOGRAM_TO_PHRASE';
export const REMOVE_PICTOGRAM_TO_PHRASE = 'REMOVE_PICTOGRAM_TO_PHRASE';

export const RESET_STATE = 'RESET_STATE';