export const FETCH_PICTOGRAMS_PENDING = 'FETCH_PICTOGRAMS_PENDING';
export const FETCH_PICTOGRAMS_ERROR = 'FETCH_PICTOGRAMS_ERROR';
export const FETCH_PICTOGRAMS_SUCCESS = 'FETCH_PICTOGRAMS_SUCCESS';

export const GET_PICTOGRAMS = 'GET_PICTOGRAMS';

export const ADD_PICTOGRAM_SUCCESS = 'ADD_PICTOGRAM_SUCCESS';
export const ADD_PICTOGRAM_ERROR = 'ADD_PICTOGRAM_ERROR';
export const UPDATE_PICTOGRAM_SUCCESS = 'UPDATE_PICTOGRAM_SUCCESS';
export const UPDATE_PICTOGRAM_ERROR = 'UPDATE_PICTOGRAM_ERROR';
export const DELETE_PICTOGRAM_SUCCESS = 'DELETE_PICTOGRAM_SUCCESS';
export const DELETE_PICTOGRAM_ERROR = 'DELETE_PICTOGRAM_ERROR';

export const CHANGED_STATUS = 'CHANGED_STATUS'

export const CLEAN_ERROR = 'CLEAN_ERROR'

export const PICTOGRAMS_ASYNC_STORAGE = 'PICTOGRAMS_ASYNC_STORAGE';

export const FAVORITES_PICTOGRAMS = 'FAVORITES_PICTOGRAMS';

export const ADD_FAVORITE = 'ADD_FAVORITE';

export const MAX_QUANTITY_OF_FAVORITES_PICTOGRAMS = 50;

export const RESET_STATE = 'RESET_STATE';